---
- Quick:
    - GitHub:
        - abbr: GH
          href: https://github.com/nicobonada
    - Tailscale ACL:
        - abbr: ACL
          href: https://github.com/nicobonada/tailscale-policy
    - Tailscale Admin:
        - abbr: TS
          href: https://login.tailscale.com/admin/machines
    - Honeycomb:
        - abbr: HC
          href: https://ui.honeycomb.io/nico-testing/environments/test/datasets/caddy
    - Cloudflare:
        - abbr: CF
          href: https://dash.cloudflare.com/
    - Backblaze:
        - abbr: B2
          href: https://secure.backblaze.com/b2_buckets.htm
    - Samba:
        - abbr: SMB
          href: smb://homelab/music
